Add more variety to bought good/bad colonists
Better-Scenes/RimConnect-mod pull request #43
Opened 2023-09-15 09:33 UTC by dispencerr

I added several additional traits that I felt were objectively good/bad to the pawn "good trait" and "bad trait" list used when good/bad colonists are purchased. "Night owl" is also added as a good trait for variety, as although it can result in a mood debuff if awake during the day, the constant mood bonus from being awake at night and the fact that they will use workbenches when other pawns are normally asleep is a net positive. All other new traits are objectively positive/negative only.

In addition, previously both trait lists only had degree "2" traits, so I added the degree "1" traits in both directions for more variety. I adjusted the code to use a traitType "dictionary" to pull traits from, preventing it from randomly choosing both the degree "1" and degree "2" trait on the same pawn.

2023-09-15 12:52 UTC, InfinitySamurai requested changes

2023-09-15 12:52 UTC, InfinitySamurai commented on Source/RimConnection/Managers/PawnCreationManager.cs
> +                }
This code is basically repeated for each generation with the only things changing being what list it's pulling from and how many it's pulling. Can we make a function that takes those 2 arguments and returns us a list of traitDefs too apply to the colonist?

2023-09-17 08:40 UTC, dispencerr commented
@InfinitySamurai I created a SelectRandomTraits function that takes the dictionary and number of traits and returns a list of traitDefs to apply to the colonist as suggested, removing repeated code. I also created a function to initialize the good and bad trait dictionaries based on the lists.

2023-10-14 12:06 UTC, InfinitySamurai approved these changes

2023-10-14 12:06 UTC, merged